services:
  postgres:
    image: postgres:16-alpine
    container_name: agent-fabric-demo-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/01-seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d shopdb"]
      interval: 3s
      timeout: 3s
      retries: 10

  mongo:
    image: mongo:7.0
    container_name: agent-fabric-demo-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./seed.mongo.js:/docker-entrypoint-initdb.d/01-seed.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      timeout: 3s
      retries: 10
